defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      title: "changethis"
      
    collections:
      updatelog:
        layout: "none"
        output: true
        permalink: /updates/:name
    home: false
    enter: false
    permalink: /:title/
    uses_img_header: false
    file_prefix: .
    header_file: "dfsf"
    includes_scripts: true