defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      title: "changethis"
    home: false
    includes_update_log: false
    uses_img_header: false
    file_prefix: .
    header_file: ""